railsProjects/timeclock/config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'login' => 'sessions#new'
  get 'home' => 'punchcards#index'
  get 'logout' => 'sessions#destroy'

  post 'login' => 'sessions#create'
  post 'sessions/new' => "sessions#create"
  post 'sessions/create' => "sessions#create"

  resources :users
  resources :punchcards

end

railsProjects/timeclock/app/models/punchcard.rb
class Punchcard < ActiveRecord::Base
	include ActiveModel::Validations
	validates :timein, :timeout, :user_id, presence: true
	validates :timein, :timeout, numericality: true
	validate :check_valid

	def check_valid
		if (timein < timeout and timein >= 0 and timeout < 24)
			return true
		else
			errors.add(:timein, "Invalid time entered. \n\tTime in: #{timein} \n\tTime out: #{timeout}")
			return false
		end
	end

end

railsProjects/timeclock/app/models/user.rb
class User < ActiveRecord::Base
	validates :username, :password, presence: true
	validates :username, uniqueness: true

	before_save :encrypt_password

	def self.authenticate(username, password)
		user = find_by_username(username)
		if user && user.password == BCrypt::Engine.hash_secret(password, user.salt)
			return user
		else
			return nil
		end
	end

	private
	def encrypt_password
		if password.present?
			self.salt = BCrypt::Engine.generate_salt
			self.password = BCrypt::Engine.hash_secret(password, self.salt)
		end
	end
end

railsProjects/timeclock/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

railsProjects/timeclock/app/controllers/punchcards_controller.rb
class PunchcardsController < ApplicationController
  before_action :set_punchcard, only: [:show, :edit, :update, :destroy]

  # GET /punchcards
  # GET /punchcards.json
  def index
    @punchcards = Punchcard.all
  end

  # GET /punchcards/1
  # GET /punchcards/1.json
  def show
  end

  # GET /punchcards/new
  def new
    @punchcard = Punchcard.new
  end

  # GET /punchcards/1/edit
  def edit
  end

  # POST /punchcards
  # POST /punchcards.json
  def create
    @punchcard = Punchcard.new(params)

    respond_to do |format|
      if @punchcard.save
        format.html { redirect_to @punchcard, notice: 'Punchcard was successfully created.' }
        format.json { render :show, status: :created, location: @punchcard }
      else
        format.html { render :new }
        format.json { render json: @punchcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /punchcards/1
  # PATCH/PUT /punchcards/1.json
  def update
    respond_to do |format|
      if @punchcard.update(punchcard_params)
        format.html { redirect_to @punchcard, notice: 'Punchcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @punchcard }
      else
        format.html { render :edit }
        format.json { render json: @punchcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /punchcards/1
  # DELETE /punchcards/1.json
  def destroy
    @punchcard.destroy
    respond_to do |format|
      format.html { redirect_to punchcards_url, notice: 'Punchcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_punchcard
      @punchcard = Punchcard.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def punchcard_params
      params.require(:punchcard).permit(:timein, :timeout, :user_id)
    end
end

railsProjects/timeclock/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.authenticate(params[:username], params[:password])
  	if user.present?
  		session[:user_id] = user.id
  		redirect_to '/home'
  	else
  		redirect_to '/login', notice: "Invalid username or password."
  	end
  end

  def destroy
  	session[:user_id] = nil
  	redirect_to '/login', notice: "Logged out"
  end
end

railsProjects/timeclock/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password)
    end
end

railsProjects/timeclock/app/helpers/application_helper.rb
module ApplicationHelper
end

railsProjects/timeclock/app/helpers/punchcards_helper.rb
module PunchcardsHelper
end

railsProjects/timeclock/app/helpers/sessions_helper.rb
module SessionsHelper
end

railsProjects/timeclock/app/helpers/users_helper.rb
module UsersHelper
end

railsProjects/timeclock/app/views/punchcards/_form.html.haml
= if :notice.present?
  %h2= notice


%form

  %label
    Start time: 
  %input(type='text' placeholder='00' id='startHour' size='2' maxlength='2')
  \:
  %input(type='text' placeholder='00' id='StartMinute' size='2' maxlength='2')

  %input(type='radio' name='startType' value='am')
    AM
  %input(type='radio' name='startType' value='pm')
    PM
  %input(type='radio' name='startType' value='millitary')
    Millitary

  %br

  %label
    Stop time: 
  %input(type='text' placeholder='00' id='endHour' size='2' maxlength='2')
  \:
  %input(type='text' placeholder='00' id='endMinute' size='2' maxlength='2')
  
  %input(type='radio' name='endType' value='am')
    AM
  %input(type='radio' name='endType' value='pm')
    PM
  %input(type='radio' name='endType' value='millitary')
    Millitary

  %br

  %input(type='button' onclick="submit()" value="submit")

  #output(style='width: 100px; height: 110px; background-color: lime')

railsProjects/timeclock/app/views/punchcards/edit.html.erb
<h1>Editing punchcard</h1>

<%= render 'form' %>

<%= link_to 'Show', @punchcard %> |
<%= link_to 'Back', punchcards_path %>

railsProjects/timeclock/app/views/punchcards/index.html.erb
<h1>Listing punchcards</h1>

<table>
  <thead>
    <tr>
      <th>Timein</th>
      <th>Timeout</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @punchcards.each do |punchcard| %>
      <tr>
        <td><%= punchcard.timein %></td>
        <td><%= punchcard.timeout %></td>
        <td><%= punchcard.user_id %></td>
        <td><%= link_to 'Show', punchcard %></td>
        <td><%= link_to 'Edit', edit_punchcard_path(punchcard) %></td>
        <td><%= link_to 'Destroy', punchcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Punchcard', new_punchcard_path %>

railsProjects/timeclock/app/views/punchcards/new.html.erb
<h1>New punchcard</h1>

<%= render 'form' %>

<%= link_to 'Back', punchcards_path %>

railsProjects/timeclock/app/views/punchcards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Timein:</strong>
  <%= @punchcard.timein %>
</p>

<p>
  <strong>Timeout:</strong>
  <%= @punchcard.timeout %>
</p>

<p>
  <strong>User:</strong>
  <%= @punchcard.user_id %>
</p>

<%= link_to 'Edit', edit_punchcard_path(@punchcard) %> |
<%= link_to 'Back', punchcards_path %>

railsProjects/timeclock/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :salt %><br>
    <%= f.text_field :salt %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsProjects/timeclock/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

railsProjects/timeclock/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Salt</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.salt %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

railsProjects/timeclock/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

railsProjects/timeclock/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Salt:</strong>
  <%= @user.salt %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>