railsProjects/apartmentApp/config/routes.rb
Rails.application.routes.draw do
  resources :users

  resources :amenities

  resources :apartments

end

railsProjects/apartmentApp/app/models/amenity.rb
class Amenity < ActiveRecord::Base
end

railsProjects/apartmentApp/app/models/apartment.rb
class Apartment < ActiveRecord::Base
	validates :cost, :bedrooms, :bathrooms, :pay_period, presence: true
	validates :bedrooms, :bathrooms, :cost, numericality: true
	validates :cost, :bedrooms, :bathrooms, numericality: { greater_than_or_equal_to: 0 }
	validates :pay_period, inclusion: { in: %w(monthly by_semester) }
end

railsProjects/apartmentApp/app/models/user.rb
class User < ActiveRecord::Base
end

railsProjects/apartmentApp/app/controllers/amenities_controller.rb
class AmenitiesController < ApplicationController
  before_action :set_amenity, only: [:show, :edit, :update, :destroy]

  # GET /amenities
  # GET /amenities.json
  def index
    @amenities = Amenity.all
  end

  # GET /amenities/1
  # GET /amenities/1.json
  def show
  end

  # GET /amenities/new
  def new
    @amenity = Amenity.new
  end

  # GET /amenities/1/edit
  def edit
  end

  # POST /amenities
  # POST /amenities.json
  def create
    @amenity = Amenity.new(amenity_params)

    respond_to do |format|
      if @amenity.save
        format.html { redirect_to @amenity, notice: 'Amenity was successfully created.' }
        format.json { render :show, status: :created, location: @amenity }
      else
        format.html { render :new }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /amenities/1
  # PATCH/PUT /amenities/1.json
  def update
    respond_to do |format|
      if @amenity.update(amenity_params)
        format.html { redirect_to @amenity, notice: 'Amenity was successfully updated.' }
        format.json { render :show, status: :ok, location: @amenity }
      else
        format.html { render :edit }
        format.json { render json: @amenity.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /amenities/1
  # DELETE /amenities/1.json
  def destroy
    @amenity.destroy
    respond_to do |format|
      format.html { redirect_to amenities_url, notice: 'Amenity was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_amenity
      @amenity = Amenity.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def amenity_params
      params.require(:amenity).permit(:amenity)
    end
end

railsProjects/apartmentApp/app/controllers/apartments_controller.rb
class ApartmentsController < ApplicationController
  before_action :set_apartment, only: [:show, :edit, :update, :destroy]

  # GET /apartments
  # GET /apartments.json
  def index
    @apartments = Apartment.all
  end

  # GET /apartments/1
  # GET /apartments/1.json
  def show
  end

  # GET /apartments/new
  def new
    @apartment = Apartment.new
  end

  # GET /apartments/1/edit
  def edit
  end

  # POST /apartments
  # POST /apartments.json
  def create
    @apartment = Apartment.new(apartment_params)

    respond_to do |format|
      if @apartment.save
        format.html { redirect_to @apartment, notice: 'Apartment was successfully created.' }
        format.json { render :show, status: :created, location: @apartment }
      else
        format.html { render :new }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /apartments/1
  # PATCH/PUT /apartments/1.json
  def update
    respond_to do |format|
      if @apartment.update(apartment_params)
        format.html { redirect_to @apartment, notice: 'Apartment was successfully updated.' }
        format.json { render :show, status: :ok, location: @apartment }
      else
        format.html { render :edit }
        format.json { render json: @apartment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apartments/1
  # DELETE /apartments/1.json
  def destroy
    @apartment.destroy
    respond_to do |format|
      format.html { redirect_to apartments_url, notice: 'Apartment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_apartment
      @apartment = Apartment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def apartment_params
      params.require(:apartment).permit(:bedrooms, :bathrooms, :cost, :monthly)
    end
end

railsProjects/apartmentApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

railsProjects/apartmentApp/app/controllers/session_controller.rb
class SessionController < ApplicationController
end

railsProjects/apartmentApp/app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :email, :password, :privlages)
    end
end

railsProjects/apartmentApp/app/helpers/amenities_helper.rb
module AmenitiesHelper
end

railsProjects/apartmentApp/app/helpers/apartments_helper.rb
module ApartmentsHelper
end

railsProjects/apartmentApp/app/helpers/application_helper.rb
module ApplicationHelper
end

railsProjects/apartmentApp/app/helpers/session_helper.rb
module SessionHelper
end

railsProjects/apartmentApp/app/helpers/users_helper.rb
module UsersHelper
end

railsProjects/apartmentApp/app/views/amenities/_form.html.erb
<%= form_for(@amenity) do |f| %>
  <% if @amenity.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@amenity.errors.count, "error") %> prohibited this amenity from being saved:</h2>

      <ul>
      <% @amenity.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :amenity %><br>
    <%= f.text_field :amenity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsProjects/apartmentApp/app/views/amenities/edit.html.erb
<h1>Editing amenity</h1>

<%= render 'form' %>

<%= link_to 'Show', @amenity %> |
<%= link_to 'Back', amenities_path %>

railsProjects/apartmentApp/app/views/amenities/index.html.erb
<h1>Listing amenities</h1>

<table>
  <thead>
    <tr>
      <th>Amenity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @amenities.each do |amenity| %>
      <tr>
        <td><%= amenity.amenity %></td>
        <td><%= link_to 'Show', amenity %></td>
        <td><%= link_to 'Edit', edit_amenity_path(amenity) %></td>
        <td><%= link_to 'Destroy', amenity, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Amenity', new_amenity_path %>

railsProjects/apartmentApp/app/views/amenities/new.html.erb
<h1>New amenity</h1>

<%= render 'form' %>

<%= link_to 'Back', amenities_path %>

railsProjects/apartmentApp/app/views/amenities/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Amenity:</strong>
  <%= @amenity.amenity %>
</p>

<%= link_to 'Edit', edit_amenity_path(@amenity) %> |
<%= link_to 'Back', amenities_path %>

railsProjects/apartmentApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ApartmentApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

railsProjects/apartmentApp/app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :privlages %><br>
    <%= f.number_field :privlages %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

railsProjects/apartmentApp/app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

railsProjects/apartmentApp/app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Username</th>
      <th>Email</th>
      <th>Password</th>
      <th>Privlages</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= user.privlages %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

railsProjects/apartmentApp/app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

railsProjects/apartmentApp/app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Privlages:</strong>
  <%= @user.privlages %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>