railsProjects/pokemonGame/config/routes.rb
Rails.application.routes.draw do
  
  get 'sessions/new'
  get 'sessions/destroy'
  get 'session/logout'

  get 'login' => 'sessions#new'
  get 'home' => 'home#index'
  get 'logout' => 'sessions#destroy'
  get 'pokemon' => 'pokemons#index'

  post 'login' => 'sessions#create'
  post 'sessions/new' => "sessions#create"
  post 'sessions/create' => "sessions#create"

  resources :users
  
  resources :user_pokemons

  resources :pokemons

end

railsProjects/pokemonGame/app/models/pokemon.rb
class Pokemon < ActiveRecord::Base
	validates :name, :attack, :sp_attack, :defence, :sp_defence, :pokedex_id, presence: true
	validates :attack, :sp_attack, :defence, :sp_defence, :pokedex_id, numericality: {greater_than_or_equal_to: 1}
	validates :name, :pokedex_id, uniqueness: true

	def self.getPokemon(pokedex_id)
		pokemon = find_pokemon_by_pokedex_id(pokedex_id)
		if pokemon.present?
			return pokemon
		else
			return nil
		end
	end

end

railsProjects/pokemonGame/app/controllers/pokemons_controller.rb
class PokemonsController < ApplicationController
  before_action :set_pokemon, only: [:show, :edit, :update, :destroy]

  # GET /pokemons
  # GET /pokemons.json
  def index
    @pokemons = Pokemon.all
  end

  # GET /pokemons/1
  # GET /pokemons/1.json
  def show
  end

  # GET /pokemons/new
  def new
    @pokemon = Pokemon.new
  end

  # GET /pokemons/1/edit
  def edit
  end

  # POST /pokemons
  # POST /pokemons.json
  def create
    @pokemon = Pokemon.new(pokemon_params)

    respond_to do |format|
      if @pokemon.save
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully created.' }
        format.json { render :show, status: :created, location: @pokemon }
      else
        format.html { render :new }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pokemons/1
  # PATCH/PUT /pokemons/1.json
  def update
    respond_to do |format|
      if @pokemon.update(pokemon_params)
        format.html { redirect_to @pokemon, notice: 'Pokemon was successfully updated.' }
        format.json { render :show, status: :ok, location: @pokemon }
      else
        format.html { render :edit }
        format.json { render json: @pokemon.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pokemons/1
  # DELETE /pokemons/1.json
  def destroy
    @pokemon.destroy
    respond_to do |format|
      format.html { redirect_to pokemons_url, notice: 'Pokemon was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pokemon
      @pokemon = Pokemon.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pokemon_params
      params.require(:pokemon).permit(:name, :attack, :sp_attack, :defence, :sp_defence, :pokedex_id)
    end
end

railsProjects/pokemonGame/app/helpers/pokemons_helper.rb
module PokemonsHelper
end

railsProjects/pokemonGame/app/views/pokemons/_form.html.haml
= form_for(@pokemon) do |f|
  = if @pokemon.errors.any?
    #error_explanation
      %h2
        = pluralize(@pokemon.errors.count, "error") 
        prohibited this pokemon from being saved:

      %ul
        = @pokemon.errors.full_messages.each do |message|
          %li= message

  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :attack
    = f.number_field :attack
  .field
    = f.label :sp_attack
    = f.number_field :sp_attack
  .field
    = f.label :defence
    = f.number_field :defence
  .field
    = f.label :sp_defence
    = f.number_field :sp_defence
  .field
    = f.label :pokedex_id
    = f.number_field :pokedex_id
  .actions
    = f.submit

railsProjects/pokemonGame/app/views/pokemons/edit.html.haml
%h1 Editing pokemon
= render 'form'
= link_to 'Show', @pokemon
= link_to 'Back', pokemons_path

railsProjects/pokemonGame/app/views/pokemons/index.html.haml
%h1 Listing pokemons

%table
  %thead
    %tr
      %th Name
      %th Attack
      %th Sp attack
      %th Defence
      %th Sp defence
      %th Pokedex id
      %th(colspan="3")
  %tbody
    = @pokemons.each do |pokemon|
      %tr
        %td= pokemon.name
        %td= pokemon.attack
        %td= pokemon.sp_attack
        %td= pokemon.defence
        %td= pokemon.sp_defence
        %td= pokemon.pokedex_id
        %td= link_to 'Show', pokemon
        %td= link_to 'Edit', edit_pokemon_path(pokemon)
        %td= link_to 'Destroy', pokemon, method: :delete, data: { confirm: 'Are you sure?' }
%br

= link_to 'New Pokemon', new_pokemon_path

railsProjects/pokemonGame/app/views/pokemons/new.html.haml
%h1 New pokemon
= render 'form'
=link_to 'Back', pokemons_path

railsProjects/pokemonGame/app/views/pokemons/show.html.haml
= if notice.present?
  %p= notice

%p 
  Name: 
  = @pokemon.name
%p 
  Attack: 
  = @pokemon.attack

%p 
  Special attack: 
  = @pokemon.sp_attack

%p 
  Defence: 
  = @pokemon.defence

%p 
  Special defence: 
  = @pokemon.sp_defence

= link_to 'Edit', edit_pokemon_path(@pokemon)
= link_to 'Back', pokemons_path